<?php

namespace App\DataFixtures;

use App\Entity\Wardrobe;
use App\Entity\Skin;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class AppFixtures extends Fixture
{
     //reference names for wardrobe
     private const JONATHAN_WARDROBE = "jonathan_s_wardrobe";
     private const MICHEL_WARDROBE = "michel_s_wardrobe";
 
     private static function wardrobeDataGenerator()
     {
         yield ["Jonathan's wardrobe", self::JONATHAN_WARDROBE];
         yield ["Michel's wardrobe", self::MICHEL_WARDROBE];
     }

    public function load(ObjectManager $manager): void
    {
        $inventoryRepo = $manager->getRepository(Wardrobe::class);

        foreach (self::wardrobeDataGenerator() as [$name, $wardrobeReference] ) {
            $wardrobe = new Wardrobe();
            $wardrobe->setName($name);
            $manager->persist($wardrobe);
            $manager->flush();

            // Once the Wardrobe instance has been saved to DB
            // it has a valid Id generated by Doctrine, and can thus
            // be saved as a future reference
            $this->addReference($wardrobeReference, $wardrobe);
        }
        // $product = new Product();
        // $manager->persist($product);
        $this -> loadSkins($manager);

    }
    
    private function loadSkins(ObjectManager $manager)
    {
        foreach (self::getSkinData() as [$wardrobeReference,$name, $rarety]) {
            $wardrobe = $this->getReference($wardrobeReference);
            $skin = new Skin();
            $skin->setName($name);
            $skin->setRarety($rarety);
            $wardrobe->addSkin($skin);
            $manager->persist($skin);
            $manager->persist($wardrobe);
        }
        $manager->flush();
    }
    
    private function getSkinData()
    {
        // Skin = [inventory ref, name, rarety];
        yield [self::JONATHAN_WARDROBE,'Supreme Dragon', "Legendary"];
        yield [self::MICHEL_WARDROBE,'LittleMan', "Epic"];
        yield [self::JONATHAN_WARDROBE,'SpeedWagon',  "Rare"];
        yield [self::JONATHAN_WARDROBE,'The World', "Unique"];
        
    }
}
