<?php

namespace App\DataFixtures;

use App\Entity\Wardrobe;
use App\Entity\Skin;
use App\Entity\Member;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class AppFixtures extends Fixture
{
     //reference names for wardrobe
     private const JONATHAN_WARDROBE = "jonathan_s_wardrobe";
     private const MICHEL_WARDROBE = "michel_s_wardrobe";
    //reference names for members
    private const JONATHAN = "jonathan";
    private const MICHEL = "michel";

     private static function wardrobeDataGenerator()
     {
         yield ["Jonathan's wardrobe", self::JONATHAN_WARDROBE,self::JONATHAN, "My little inventory <3"];
         yield ["Michel's wardrobe", self::MICHEL_WARDROBE, self::MICHEL, "Da Collection"];
     }

     private static function memberDataGenerator(){
        yield ["Jonathan", self::JONATHAN];
        yield["Michel", self::MICHEL];
     }

    public function load(ObjectManager $manager): void
    {
        $inventoryRepo = $manager->getRepository(Wardrobe::class);
        $memberRepo = $manager->getRepository(Member::class);

        foreach (self::memberDataGenerator() as [$name, $memberReference]){
            $member = new Member();
            $member->setName($name);
            $manager->persist($member);
            $manager->flush();

            $this->addReference($memberReference, $member);
        }
        foreach (self::wardrobeDataGenerator() as [$name, $wardrobeReference, $memberReference, $description] ) {
            $member = $this->getReference($memberReference);
            $wardrobe = new Wardrobe();
            $wardrobe->setName($name);
            $wardrobe->setDescription($description);
            $member->addWardrobe($wardrobe);
            $manager->persist($wardrobe);
            $manager->persist($member);
            $manager->flush();

            // Once the Wardrobe instance has been saved to DB
            // it has a valid Id generated by Doctrine, and can thus
            // be saved as a future reference
            $this->addReference($wardrobeReference, $wardrobe);
        }
        // $product = new Product();
        // $manager->persist($product);
        $this -> loadSkins($manager);

    }
    
    private function loadSkins(ObjectManager $manager)
    {
        foreach (self::getSkinData() as [$wardrobeReference,$name, $rarety]) {
            $wardrobe = $this->getReference($wardrobeReference);
            $skin = new Skin();
            $skin->setName($name);
            $skin->setRarety($rarety);
            $wardrobe->addSkin($skin);
            $manager->persist($skin);
            $manager->persist($wardrobe);
        }
        $manager->flush();
    }
    
    private function getSkinData()
    {
        // Skin = [inventory ref, name, rarety];
        yield [self::JONATHAN_WARDROBE,'Supreme Dragon', "Legendary"];
        yield [self::MICHEL_WARDROBE,'LittleMan', "Epic"];
        yield [self::JONATHAN_WARDROBE,'SpeedWagon',  "Rare"];
        yield [self::JONATHAN_WARDROBE,'The World', "Unique"];
        
    }
}
